" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=InconsolataForPowerline:h20       " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.

set guioptions-=T                 " Hide toolbar.

set background=dark              " Background.
set lines=25 columns=100          " Window dimensions.
colorscheme topfunky-light
colorscheme Tomorrow-Night

" For OS X 10.7 and later:
set guioptions-=r                 " Don't show right scrollbar


