" jens' vim config, poorly maintained...

set nocompatible                  " Must come first because it changes other options.

"""""""""""" Vundle Config
filetype off "required by vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

"Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'scrooloose/syntastic'
"Plugin 'kien/ctrlp.vim'
"Plugin 'bling/vim-airline'
Plugin 'vim-scripts/Solarized'
"Plugin 'fatih/vim-go'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'rust-lang/rust.vim'

call vundle#end()            " required
filetype plugin indent on    " required

"""""""""""""""" Normal configuration
syntax enable                     " Turn on syntax highlighting.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp/,.   " Keep swap files in one location

" Tab Stuff
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs

" Satusbar
set laststatus=2                  " Show the status line all the time

" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P


" Set the colorscheme
set background=light
colorscheme solarized
" colorscheme pink
" colorscheme topfunky-light
" colorscheme Tomorrow
" colorscheme Tomorrow-Night-Blue
" colorscheme Tomorrow-Night-Bright
" colorscheme Tomorrow-Night-Eighties


" Show whitespace characters
" set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set listchars=tab:~~,trail:•,extends:>,precedes:<
set list

nnoremap <F11> :set list! list?<CR>

" Set the <leader> key:
let mapleader=","

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" get an empty buffer
map <leader>nb :bp<bar>sp<bar>bn<bar>bd<CR>

" Automatic fold settings for specific files. Uncomment to use.
autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" Map identation key for visual mode
vmap > >gv
vmap < <gv

" Map the Tab to it also:
vmap <Tab> >gv
vmap <A-Tab> <gv

