# Source the main .profile first
. ~/.profile

# Basic zsh settings
export HISTSIZE=100000
export SAVEHIST=100000
export INC_APPEND_HISTORY=true
export HIST_IGNORE_DUPS=true

# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/jns/.zsh/completions:"* ]]; then export FPATH="/Users/jns/.zsh/completions:$FPATH"; fi

# Fuzzy matching of completions for when you mistype them
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 10 numeric

# No correction of misspelled commands and arguments
unsetopt correct
unsetopt correct_all

# Initialize zsh completions (added by deno install script)
autoload -Uz compinit
compinit

# init starship
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"

# fzf
source <(fzf --zsh)

