# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

##############################################################################
# export ZSH_THEME="Soliah"
# export ZSH_THEME="afowler"
# export ZSH_THEME="alanpeabody"
# export ZSH_THEME="apple"
# export ZSH_THEME="arrow"
# export ZSH_THEME="aussiegeek"
# export ZSH_THEME="awesomepanda"
export ZSH_THEME="bira"
# export ZSH_THEME="blinks"
# export ZSH_THEME="candy"
# export ZSH_THEME="clean"
# export ZSH_THEME="cloud"
# export ZSH_THEME="crunch"
# export ZSH_THEME="cypher"
# export ZSH_THEME="dallas"
# export ZSH_THEME="darkblood"
# export ZSH_THEME="daveverwer"
# export ZSH_THEME="dieter"
# export ZSH_THEME="dogenpunk"
# export ZSH_THEME="dpoggi"
# export ZSH_THEME="dst"
# export ZSH_THEME="dstufft"
# export ZSH_THEME="duellj"
# export ZSH_THEME="eastwood"
# export ZSH_THEME="edvardm"
# export ZSH_THEME="evan"
# export ZSH_THEME="example"
# export ZSH_THEME="fino"
# export ZSH_THEME="fishy"
# export ZSH_THEME="flazz"
# export ZSH_THEME="fletcherm"
# export ZSH_THEME="fox"
# export ZSH_THEME="frisk"
# export ZSH_THEME="funky"
# export ZSH_THEME="fwalch"
# export ZSH_THEME="gallifrey"
# export ZSH_THEME="gallois"
# export ZSH_THEME="garyblessington"
# export ZSH_THEME="gentoo"
# export ZSH_THEME="geoffgarside"
# export ZSH_THEME="gnzh"
# export ZSH_THEME="gozilla"
# export ZSH_THEME="humza"
# export ZSH_THEME="imajes"
# export ZSH_THEME="jbergantine"
# export ZSH_THEME="jispwoso"
# export ZSH_THEME="jnrowe"
# export ZSH_THEME="jonathan"
# export ZSH_THEME="josh"
# export ZSH_THEME="jreese"
# export ZSH_THEME="jtriley"
# export ZSH_THEME="juanghurtado"
# export ZSH_THEME="kardan"
# export ZSH_THEME="kennethreitz"
# export ZSH_THEME="kolo"
# export ZSH_THEME="kphoen"
# export ZSH_THEME="lambda"
# export ZSH_THEME="linuxonly"
# export ZSH_THEME="lukerandall"
# export ZSH_THEME="macovsky-ruby"
# export ZSH_THEME="macovsky"
# export ZSH_THEME="maran"
# export ZSH_THEME="mgutz"
# export ZSH_THEME="mh"
# export ZSH_THEME="mikeh"
# export ZSH_THEME="miloshadzic"
# export ZSH_THEME="minimal"
# export ZSH_THEME="mortalscumbag"
# export ZSH_THEME="mrtazz"
# export ZSH_THEME="murilasso"
# export ZSH_THEME="muse"
# export ZSH_THEME="nanotech"
# export ZSH_THEME="nebirhos"
# export ZSH_THEME="nicoulaj"
# export ZSH_THEME="norm"
# export ZSH_THEME="obraun"
# export ZSH_THEME="philips"
# export ZSH_THEME="pmcgee"
# export ZSH_THEME="pygmalion"
# export ZSH_THEME="re5et"
# export ZSH_THEME="rgm"
# export ZSH_THEME="risto"
# export ZSH_THEME="rixius"
# export ZSH_THEME="rkj-repos"
# export ZSH_THEME="rkj"
# export ZSH_THEME="robbyrussell"
# export ZSH_THEME="sammy"
# export ZSH_THEME="simple"
# export ZSH_THEME="skaro"
# export ZSH_THEME="smt"
# export ZSH_THEME="sorin"
# export ZSH_THEME="sporty_256"
# export ZSH_THEME="steeef"
# export ZSH_THEME="sunaku"
# export ZSH_THEME="sunrise"
# export ZSH_THEME="superjarin"
# export ZSH_THEME="suvash"
# export ZSH_THEME="takashiyoshida"
# export ZSH_THEME="terminalparty"
export ZSH_THEME="theunraveler"
# export ZSH_THEME="tjkirch"
# export ZSH_THEME="tonotdo"
# export ZSH_THEME="trapd00r"
# export ZSH_THEME="wedisagree"
# export ZSH_THEME="wezm+"
# export ZSH_THEME="wezm"
# export ZSH_THEME="wuffers"
# export ZSH_THEME="xiong-chiamiov-plus"
# export ZSH_THEME="xiong-chiamiov"
# export ZSH_THEME="ys"
# export ZSH_THEME="zhann"

##############################################################################

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(git textmate ruby github brew ssh-agent osx rails rails3 git-flow gem bundler cake lol)
# plugins=(textmate ruby brew osx rails git-flow gem bundler cake rake  lol gitfast git-extras gitignore github coffee bower rvm vagrant)
plugins=(brew osx git-flow cake git cucknorris battery autoenv coffee bower)
# plugins=(osx git github)

source $ZSH/oh-my-zsh.sh

# resolve conflict with go's gb tool
unalias gb

# Customize to your needs...

export HISTSIZE=100000
export SAVEHIST=100000
export INC_APPEND_HISTORY=true
export HIST_IGNORE_DUPS=true

# Fuzzy matching of completions for when you mistype them
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 10 numeric

# No correction of misspelled commands and arguments
unsetopt correct
unsetopt correct_all

# git flow completions
source ${HOMEBREW}/share/zsh/site-functions

# actual profile stuff
# source ${HOME}/.zprofile

alias dokku='bash $HOME/.dokku/contrib/dokku_client.sh'

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /Users/jns/Projects/arnold/repertoire/text-fields/node_modules/ember-electron/node_modules/electron-forge/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /Users/jns/Projects/arnold/repertoire/text-fields/node_modules/ember-electron/node_modules/electron-forge/node_modules/tabtab/.completions/electron-forge.zsh